#!/usr/bin/env python3
"""Embed the Control Room page into C++ as chunked string literals.

The page is a build input, not a runtime file: a missing dashboard should fail
the build rather than surprise an operator at a broken moment. This mirrors
tools/generate_phase7_schemas.py rather than introducing a second codegen shape.

Bytes are emitted as three-digit octal escapes wherever they are not plainly
printable ASCII. Octal escapes are exactly three digits, so they terminate
without depending on what follows; \\xNN does not, and would swallow the next
character whenever it happens to be a hex digit.

Literals are chunked because MSVC rejects a single string literal longer than
16380 characters (C2026), and an escaped page passes that comfortably.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path

# Well under the 16380-character MSVC limit even if every source byte in a
# chunk expands to a four-character octal escape.
CHUNK_BYTES = 2048

_SIMPLE = {
    ord("\n"): "\\n",
    ord("\t"): "\\t",
    ord("\r"): "\\r",
    ord("\\"): "\\\\",
    ord('"'): '\\"',
    # Escaped so no accidental "??x" pair can be read as a trigraph by a
    # compiler still honouring them.
    ord("?"): "\\?",
}


def escape(chunk: bytes) -> str:
    out = []
    for byte in chunk:
        if byte in _SIMPLE:
            out.append(_SIMPLE[byte])
        elif 0x20 <= byte < 0x7F:
            out.append(chr(byte))
        else:
            out.append("\\{:03o}".format(byte))
    return "".join(out)


def render_source(page: bytes, page_path: str) -> str:
    chunks = [page[i:i + CHUNK_BYTES] for i in range(0, len(page), CHUNK_BYTES)]
    lines = [
        "// Generated by tools/generate_ui_app.py. Do not edit.",
        f"// Source: {page_path}",
        f"// Bytes: {len(page)}",
        f"// SHA-256: {hashlib.sha256(page).hexdigest()}",
        "",
        '#include "didi/mcp/control_room_app.hpp"',
        "",
        "namespace didi {",
        "namespace mcp {",
        "namespace {",
        "",
        "const char* const kChunks[] = {",
    ]
    for chunk in chunks:
        lines.append(f'    "{escape(chunk)}",')
    lines.extend(
        [
            "};",
            "",
            "}  // namespace",
            "",
            "const std::string& controlRoomHtml() {",
            "    static const std::string* const page = [] {",
            "        auto* joined = new std::string();",
            f"        joined->reserve({len(page)});",
            "        for (const char* chunk : kChunks) {",
            "            joined->append(chunk);",
            "        }",
            "        return joined;",
            "    }();",
            "    return *page;",
            "}",
            "",
            "}  // namespace mcp",
            "}  // namespace didi",
            "",
        ]
    )
    return "\n".join(lines)


HEADER = """// Generated by tools/generate_ui_app.py. Do not edit.
#pragma once

#include <string>

namespace didi {
namespace mcp {

// The Control Room page, embedded at build time from resources/control_room.html.
// Served as the ui://didi/control-room resource to hosts that negotiated the
// io.modelcontextprotocol/ui extension. See docs/CONTROL_ROOM_DESIGN.md.
const std::string& controlRoomHtml();

}  // namespace mcp
}  // namespace didi
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--page", required=True, type=Path)
    parser.add_argument("--header", required=True, type=Path)
    parser.add_argument("--source", required=True, type=Path)
    args = parser.parse_args()

    page = args.page.read_bytes()
    if not page:
        raise SystemExit(f"{args.page} is empty; the Control Room page is required")

    args.header.parent.mkdir(parents=True, exist_ok=True)
    args.source.parent.mkdir(parents=True, exist_ok=True)
    args.header.write_text(HEADER, encoding="utf-8")
    args.source.write_text(
        render_source(page, args.page.as_posix()), encoding="utf-8"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
